### ISSUE TITLE
Missing image on Lesson 3 notebook

### ISSUE THREAD

**Issue by henriqueribeiro** [Yorko/mlcourse_open#169]
Hey,

Image _credit_scoring_toy_tree_english.png_ is missing on the topic3_decision_trees_kNN notebook.

**Comment by Yorko** [comment]
Hi! Thanks, fixed that.

**Comment by henriqueribeiro** [comment]
Nice! Just noticed that _topic3_credit_scoring_entropy_ is also missing

**Comment by Yorko** [comment]
Okay, thank you, when I have time, I'll check all images :)
