### ISSUE TITLE
Решение вопроса 5.11 не стабильно

### ISSUE THREAD

**Issue by coodix** [Yorko/mlcourse_open#22]
Даже при выставленных random_state параметрах, best_score лучшей модели отличается от вариантов в ответах.

Подтверждено запуском несколькими участниками.

Возможно влияют конкретные версии пакетов на расчеты.

Могу приложить ipynb, на котором воспроизводится.

**Comment by Yorko** [comment]
Там вроде разница в 3 знаке, пока не будем править, в следующей версии задания поменяем RandomizedSearchCV на GridSearchCV

**Comment by coodix** [comment]
Разница в десятых.
