### ISSUE TITLE
Короткая инструкция по работе с материалами курса средствами GItHub

### ISSUE THREAD

**Issue by adyomin** [Yorko/mlcourse_open#3]
Добрый день!

Во-первых, я хотел бы сказать, что вы большие молодцы, что делаете этот курс!  Основательность с который вы его запустили впечатляет!

Во-вторых, я хотел бы предложить небольшое дополнение, а именно добавить короткую инструкцию о том, как работать с материалами курса средствами Git/GitHub.  Я думаю не все ваши слушатели умеют работать c Git/GitHub.  По опыту прошлогоднего курса Юрия в ВШЭ, где он так же выкладывал материалы на GitHub, было совсем не очевидно как корректно обновлять их, не теряя собственных заметок в лекциях.

Я догадываюсь, что скорее всего нужно сделать Fork / Clone, наверное, сделать свой бранч(?) а потом [как-то так](http://stackoverflow.com/questions/7200614/how-to-merge-remote-master-to-local-branch), но хотелось бы знать наверняка.  Возможно, это пригодиться и другим.

С наилучшими,
Андрей

**Comment by Yorko** [comment]
Приветствую!

Описывать это еще раз будет затруднительно. Советую пройти интерактивный онлайн-тьюториал типа [TryGit](https://try.github.io/levels/1/challenges/1) или [GitHowTo](https://githowto.com/ru), если первого не хватит.
Я согласен, работать с GitHub поначалу сложно, особенно, если надо что-то смерджить. Тьюториалы хороши своим подходом "learn by doing".

**Comment by Yorko** [comment]
Материалов по Git/GitHub таже очень много на Хабре. Но если кто-то хочет сделать такую инструкцию в виде тетрадке – ок, делайте pull request.
