### ISSUE TITLE
Яндекс&МФТИ, Coursera, Final project - Идентификация пользователей

### ISSUE THREAD

**Issue by levbed** [Yorko/mlcourse_open#330]
Здравствуйте! Уточните пожалуйста, какова форма ответа в задании 2 недели, вопрос 2:
"Распределено ли нормально число уникальных сайтов в сессии?". В форме нет четких указаний на формулировку ответа, варианты "Нет", "No", значение статистики и p-value критерия Шапиро-Вилка не подходят...
Может, я неверно посчитал, но ведь так и не понять :)

**Comment by Yorko** [comment]
форма ответа Yes/No. Это не Issue – на подобные вопросы отвечают менторы специализации.
