### ISSUE TITLE
/assignments_demo/assignment04_habr_popularity_ridge.ipynb - Опечатка в тексте задания

### ISSUE THREAD

**Issue by pavel-petkun** [Yorko/mlcourse_open#345]
"Инициализируйте DictVectorizer с параметрами по умолчанию.
Примените метод fit_transform к X_train['title'] и метод transform к X_valid['title'] и X_test['title']"

Скорее всего здесь опечатка: должно быть X_train[feats], X_valid[feats], X_test[feats]

**Comment by Yorko** [comment]
Спасибо, [пофиксил](https://github.com/Yorko/mlcourse_open/commit/4c288f6a0c15286c7d8fb6c3baa717c1ac0e78fa).
