### ISSUE TITLE
Parsing error for topic9_part2_facebook_prophet.ipynb

### ISSUE THREAD

**Issue by AdityaSoni19031997** [Yorko/mlcourse_open#347]
This notebook isn't rendering in nbviewer nor on Github nor after uploading it to binder..

https://nbviewer.jupyter.org/github/Yorko/mlcourse_open/blob/master/jupyter_english/topic09_time_series/topic9_part2_facebook_prophet.ipynb

there's an extra i at the beginning of the notebook(had checked the raw file)

Even removing that, the nbs isn't opening..

**Comment by Yorko** [comment]
thanks, fixed that

**Comment by Yorko** [comment]
[nbviewer](https://nbviewer.jupyter.org/github/Yorko/mlcourse_open/blob/master/jupyter_english/topic09_time_series/topic9_part2_facebook_prophet.ipynb?flush_cache=true)

**Comment by AdityaSoni19031997** [comment]
Thanks Yorko

**Comment by AdityaSoni19031997** [comment]
But the error is still there...

**Comment by sarzhann** [comment]
Hi!
Am I needed in this conversation?)

сб, 4 авг. 2018 г., 22:49 Aditya Soni <notifications@github.com>:

**Comment by AdityaSoni19031997** [comment]
Hi there, Can you fix that error which that nbs has..
I guess (not sure) that the notebook isn't having correct ending as well..
Thanks.

**Comment by Yorko** [comment]
Fixed that, [nbviewer](https://nbviewer.jupyter.org/github/Yorko/mlcourse_open/blob/master/jupyter_english/topic09_time_series/topic9_part2_facebook_prophet.ipynb). Smth strange.. it worked first time in browser, but not locally. Now it should be fine. 

ps. @AdityaSoni19031997 still don't know why you mentioned Nurzhan here :)

**Comment by AdityaSoni19031997** [comment]
I didn't , I thought you forwarded him this..
But thanks for the quick response!!

**Comment by sarzhann** [comment]
Ok guys)
Have a nice day !

сб, 4 авг. 2018 г., 23:32 Aditya Soni <notifications@github.com>:
