### ISSUE TITLE
week 3 workbooks / hw dot not found

### ISSUE THREAD

**Issue by sudodoki** [Yorko/mlcourse_open#78]
Possibly can be fixed by
```RUN apt-get install graphviz```

**Comment by Yorko** [comment]
testing

**Comment by Yorko** [comment]
Одно это не помогло, нужно еще прописать путь к dot. Хочешь у себя локально попробовать и послать пулл реквест, если удастся?

**Comment by sudodoki** [comment]
Локально у себя поправил через
```
docker exec -it контейнер_айди /bin/bash
apt-get update
apt-get install graphviz
```
так что к сожалению could not reproduce больше. 😿

**Comment by Yorko** [comment]
fixed
